### ISSUE TITLE
System.AggregateException: Failed to call SymLoadModuleEx

### ISSUE THREAD

**Issue by Symbai** [Akaion/Bleak#22]
CreateThread fails on an UWP process, on all injectors (not bleak's fault), so I've tried manualmap using Bleak. I received the following exception. Please note that it IS possible using CheatEngine to inject the dll which also falls back to manual map the dll (bleak's fault):

```
System.AggregateException: 'Failed to call SymLoadModuleEx with error code 27.BoolToValueConverter`1[[Syst)'

PInvokeException: Failed to call SymLoadModuleEx with error code 2

  StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Bleak.ProgramDatabase.PdbFile..ctor(ManagedModule module, Boolean isWow64)
   at Bleak.RemoteProcess.ManagedProcess.<.ctor>b__7_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Bleak.Injection.Methods.ManualMap.EnableExceptionHandling()
   at Bleak.Injection.Methods.ManualMap.Inject()
   at Bleak.Injection.InjectionManager.InjectDll()
   at Bleak.Injector.InjectDll()
```

Code:
```
using (var injector = new Injector("process_uwp", path, InjectionMethod.ManualMap, InjectionFlags.None))
{
    // Inject the DLL into the remote process

    var dllBaseAddress = injector.InjectDll();

    // Eject the DLL from the process

    injector.EjectDll();
}
```

**Comment by Akaion** [comment]
From your provided stacktrace it appears the API call to SymLoadModuleEx was passed an invalid file path, which means the PDB for your Windows version wasn't downloaded correctly or wasn't downloaded at all. Can you check %temp%/Bleak/PDB and let me know the contents of the folder? If there is a file, can you tell me its size?

**Comment by Akaion** [comment]
Okay so after a bit of testing I've found that the issue you are experiencing is due to the file not being downloaded correctly. I'll have to implement some sort of system to check if the file was downloaded correctly and re download it if not (without a hit on performance.)

**Comment by Symbai** [comment]
I've tried it again, now it has downloaded one file (not sure if its still downloading this file) but keeps freezing for 20 minutes now.

ntdll.pdb-cfd10e5f223fee5f26227cb82510fedc-1.pdb with size 1.532kb

Does it need the pdb files? Is there a way to skip downloading them?

**Comment by Akaion** [comment]
No you can't skip the PDB downloading, it's needed to call unexported functions from ntdll.
